#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
First, install the latest release of Python wrapper: $ pip install ovh
'''
import json
import ovh
import argparse

client = ovh.Client()

parser = argparse.ArgumentParser(description='Adds a record to a domain with OVH\'s DNS API.')

parser.add_argument('domain', metavar='domain', help='domain to add a record')
parser.add_argument('type',metavar='type', help='type of the record (A, AAAA, CNAME...)')
parser.add_argument('subdomain', metavar='subdomain', help='subdomain for the record')
parser.add_argument('target', metavar='target', help='Target of the record')
parser.add_argument('--ttl', metavar='ttl', type=int, help='TTL for the record')

args = parser.parse_args()

result = client.post('/domain/zone/'+args.domain+'/record', 
    fieldType=args.type, # Resource record Name (type: zone.NamedResolutionFieldTypeEnum)
    subDomain=args.subdomain, # Resource record subdomain (type: string)
    target=args.target, # Resource record target (type: string)
    ttl=args.ttl, # Resource record ttl (type: long)
)

print((json.dumps(result, indent=4)))

# refresh
result = client.post('/domain/zone/'+args.domain+'/refresh')
print ((json.dumps(result, indent=4)))
