#!/usr/bin/env bash
#
# tek - Upload text to teknik.io.

[[ -f $1 ]] ||
    exit 1

: https://api.teknik.io/v1/Paste
: "$(curl -s --data-urlencode "code=$(< "$1")" "$_")"
: "${_/*url\":}"
: "${_/,*}"

printf '%s\n' "${_//\"}"
